title: Raekwon Williams
logo: assets/img/20240614.jpg
description: Detail-oriented and analytical professional with experience in data analysis, database management, and technical operations.
theme: jekyll-theme-minimal
