title: Raekwon Williams
logo: assets/img/20240614_135532.jpg
description: Detail-oriented and analytical professional with experience in data analysis, database management, and technical operations. Seeking to leverage my technical background and data analytics skills to grow and excel in an analytical role.
theme: jekyll-theme-minimal
